version: '3'
services:
  node-app:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - ./.env
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=docker
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
